### PR TITLE
Adldap2, unified class namings, minor improvements

### PR DESCRIPTION
**Pull request by xelan**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |

Hi Loic!

This PR is a collection of commits I've made to my fork of ZtecSecurityActiveDirectoryBundle.
- Adldap2 (4.x branch), maintained by Steve Bauman et al. is used instead of the non-working and apparently unmaintained adldap/adlap library
- The services.yml is cleaned up, class names are used directly as proposed by the Symfony Best Practices E-Book
- Code style and documentation is improved
- German translations for the error messages are added
- The class naming is unified between Authentication, Factory and User components (adUser → AdUser, adUserProvider → AdUserProvider)

The last point is a small, but BC-breaking change: Users **have to change the User entity class** in security.yml:

``` yaml
Ztec\Security\ActiveDirectoryBundle\Security\User\AdUser : plaintext
```

I tested my fork with Symfony 2.3 and 2.7.

### CODE REVIEW

**Comment by ztec** [comment]
I takelook, test and merge it if all is ok.
A new version will be tagged because of the bc-break.

Thanks for your work.

**Comment by xelan** [comment]
Thanks :+1:

**Comment by ztec** [comment]
@xelan I incorporated your changes into a new branch 1.x.
I used the "breaking change" reason to rename the project in order to remove my name from it
All configuration have now **"riper"** instead of **"ztec"** in namespace.  You can test it using the following require 

```
 "riper/security-active_directory": "1.x-dev"
```

replace all **"ztec"** occurrences in configuration by **"riper"**

can you try on your side, tell me if it's running like your version was. 
it's ok on my side.

After that, I close this PR (because the master cannot evolve due to legacy requirements)
and push a tag to create the first 1.0 release ^^  

ps : Your commits are intact and still authored by you, but i accidentally "swallowed" one in a git operation. I hope you don't mind.If yes, i can re-do some stuff to get it back :-)

**Comment by xelan** [comment]
As far as I tested (Symfony 2.3.32 with PHP 5.4.41, Symfony 2.7.4 with PHP 5.4.41 and PHP 5.6.13) the authentication via AD is working fine :smile: Name, email and role retrieval also works as expected.
Note: I had to delete the cache manually via `rm -rf app/cache/*` after `composer update`, `php app/console cache:clear` was not sufficient.

**Comment by ztec** [comment]
I had the same issue about the cache 
A session clear is also required. (incomplete objects deserialized because of the renaming)

For me it's enough. I'll create the new version shortly, then I close this MR.

Thanks for your feedback and again, thanks a lot for your work :-)

**Comment by ztec** [comment]
This PR is pulled into v1.x branch !

**Pull request closed without merging**
